# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ego' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ego
	pod 'AFNetworking', '~> 3.0'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod "PubNub", "~> 4"
    pod 'NewRelicAgent', '5.9.0'
    pod 'SAMKeychain'
    #pod 'GradientLoadingBar', '~> 1.0'

  target 'EgoTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'AFNetworking', '~> 3.0'
    pod 'GoogleMaps'
    
  end

  target 'EgoUITests' do
    inherit! :search_paths
    # Pods for testing
	pod 'AFNetworking', '~> 3.0'
  end

end
